### ISSUE TITLE
Shift Calendars display error message on Safari

### ISSUE THREAD

**Issue by 826national** [davidhabib/Volunteers-for-Salesforce#119] opened 2014-10-23 01:24 UTC
Hello,

The Shift Calendars are displaying an error message -- "undefined NaN" -- and no Shifts information when trying to navigate between months using the arrow keys. This happens on Safari v. 8.0. I've attached an image of what it looks like. Please fix as soon as you can, as our chapters' volunteers currently sign up on these calendars and many of them use Safari as a browser.

Thanks!
Cooper

![calendar](https://cloud.githubusercontent.com/assets/8248559/4746961/0a411bec-5a53-11e4-8728-aa4f480531d7.png)

**Comment by davidhabib** [comment] 2015-07-16 22:52
i cannot reproduce on OSX 10 or iOS 8, so I a closing.

**Closed by davidhabib** 2015-07-16 22:52 UTC
Labels: Defect, Medium Priority
